name: table_editor

services:
  reverse_proxy:
    # Maps urls to ports to various services.
    # Main entry point for external clients.
    build: ReverseProxy
    image: ${DOCKER_USERNAME}/${DOCKER_REPOSITORY}_reverse_proxy:${DOCKER_VERSION_TAG-latest}
    ports:
      - ${TABLE_EDITOR_HTTP_PORT-8080}:8080
      - ${TABLE_EDITOR_HTTPS_PORT-4430}:4430
    environment:
      TABLE_EDITOR_FRONTEND_PORT: ${TABLE_EDITOR_FRONTEND_PORT-3000}
      TABLE_EDITOR_WS_PORT: ${TABLE_EDITOR_WS_PORT-4000}
    depends_on:
      - frontend
      - rest_api
      - web_socket_server

  rest_api:
    # Provides a RESTful API for interfacing with the database.
    build: RestAPI
    image: ${DOCKER_USERNAME}/${DOCKER_REPOSITORY}_rest_api:${DOCKER_VERSION_TAG-latest}
    depends_on:
      database:
        condition: service_healthy
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_MILLIS: ${JWT_EXPIRATION_MILLIS}

  web_socket_server:
    # Handles web sockets for providing real-time interaction with clients.
    # Built in Rust.
    build: WebSocketServer
    image: ${DOCKER_USERNAME}/${DOCKER_REPOSITORY}_web_socket_server:${DOCKER_VERSION_TAG-latest}
    ports:
      - ${TABLE_EDITOR_WS_PORT-4000}:4000
    environment:
      TABLE_EDITOR_FRONTEND_PORT: ${TABLE_EDITOR_FRONTEND_PORT-3000}
      TABLE_EDITOR_WS_PORT: ${TABLE_EDITOR_WS_PORT-4000}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      database:
        condition: service_healthy
  
  frontend:
    # Frontend code to serve to client.
    # Built using Vite, served with nginx
    build: Frontend
    image: ${DOCKER_USERNAME}/${DOCKER_REPOSITORY}_frontend:${DOCKER_VERSION_TAG-latest}
    depends_on:
      - web_socket_server
    environment:
      TABLE_EDITOR_FRONTEND_PORT: ${TABLE_EDITOR_FRONTEND_PORT-3000}
      TABLE_EDITOR_WS_PORT: ${TABLE_EDITOR_WS_PORT-4000}

  database:
    # PostgreSQL database
    build: Database
    image: ${DOCKER_USERNAME}/${DOCKER_REPOSITORY}_database:${DOCKER_VERSION_TAG-latest}
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

volumes:
  db-data:
