name: table_editor

services:
  reverse_proxy:
    # Maps urls to ports to various services.
    # Main entry point for external clients.
    container_name: reverse_proxy
    build: ReverseProxy
    ports:
      - ${TABLE_EDITOR_HTTP_PORT-8080}:8080
    environment:
      TABLE_EDITOR_FRONTEND_PORT: ${TABLE_EDITOR_FRONTEND_PORT-3000}
      TABLE_EDITOR_WS_PORT: ${TABLE_EDITOR_WS_PORT-4000}

  web_socket_server:
    # Handles web sockets for providing real-time interaction with clients.
    # Built in Rust.
    container_name: web_socket_server
    build: WebSocketServer
    ports:
      - ${TABLE_EDITOR_WS_PORT-4000}:4000
    environment:
      TABLE_EDITOR_FRONTEND_PORT: ${TABLE_EDITOR_FRONTEND_PORT-3000}
      TABLE_EDITOR_WS_PORT: ${TABLE_EDITOR_WS_PORT-4000}
  
  frontend:
    # Frontend code to serve to client.
    # Built using Vite, served with nginx
    container_name: frontend
    build: Frontend
    depends_on:
      - web_socket_server
    environment:
      TABLE_EDITOR_FRONTEND_PORT: ${TABLE_EDITOR_FRONTEND_PORT-3000}
      TABLE_EDITOR_WS_PORT: ${TABLE_EDITOR_WS_PORT-4000}
